name: tapis-dev
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tapis
    ports:
      - "5432:5432"
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    environment:
      PORT: 8000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tapis
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./server:/code/server/
