name: tapis-dev
services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./server:/code/server/
